security:
    encoders:
        Crm\MainBundle\Entity\ActUser:
            algorithm: plaintext

    role_hierarchy:
        ROLE_DRIVER:  [ROLE_USER]
#        ROLE_COMPANY: [ROLE_USER]
#        ROLE_ADMIN:   [ROLE_DRIVER, ROLE_COMPANY]

#    providers:
#        in_memory:
#            memory:
#                users:
#                    user:  { password: userpass, roles: [ 'ROLE_USER' ] }
#                    admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }
    providers:
        main:
            entity: { class: CrmMainBundle:ActUser, property: username }
    firewalls:
        main:
            pattern: ^/
            form_login:
                check_path: /login_submit
                login_path: /login
                default_target_path: /activate-list
            logout:
                path:   /logout
                target: /
            remember_me:
                key:      "%secret%"
                lifetime: 31536000
                path:     /
                domain:   ~
            anonymous: ~

    access_control:
        - { path: /.*, role: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: /admin, role: ROLE_ADMIN }